CREATE TABLE IF NOT EXISTS labels_tasks (
    id INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    label_id INTEGER NOT NULL REFERENCES labels,
    task_id INTEGER NOT NULL REFERENCES tasks,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);